#!/bin/bash

I_SAMPLE_SIZE_MIN=1
I_SAMPLE_SIZE_MAX=20
#I_SAMPLE_SIZE_MIN=15
#I_SAMPLE_SIZE_MAX=15

# I_BOOTSTRAP_REPETITION_MIN=1
# I_BOOTSTRAP_REPETITION_MAX=100
I_BOOTSTRAP_REPETITION_MIN=51
I_BOOTSTRAP_REPETITION_MAX=100

for (( I_SAMPLE_SIZE=${I_SAMPLE_SIZE_MIN}; I_SAMPLE_SIZE <= ${I_SAMPLE_SIZE_MAX}; I_SAMPLE_SIZE += 1 ))
do
    for (( I_BOOTSTRAP_REPETITION=${I_BOOTSTRAP_REPETITION_MIN}; I_BOOTSTRAP_REPETITION <= ${I_BOOTSTRAP_REPETITION_MAX}; I_BOOTSTRAP_REPETITION += 1 ))
    do
        export I_SAMPLE_SIZE=${I_SAMPLE_SIZE}
        export I_BOOTSTRAP_REPETITION=${I_BOOTSTRAP_REPETITION}
        mysbatch /home/mwang8/ukbb-cca/scripts/slurm_job_python.sh
    done
done
