#!/bin/bash

N_PCS="100 100"

I_SAMPLE_SIZE_MIN=1
I_SAMPLE_SIZE_MAX=20

I_BOOTSTRAP_REPETITION_MIN=1
I_BOOTSTRAP_REPETITION_MAX=50

N_SAMPLE_SIZES=30
N_BOOTSTRAP_REPETITIONS=100

FNAME_DISPATH_SCRIPT="dispatch_job.sh" # assumes all scripts are in same directory
FNAME_CCA_SCRIPT="cca_sample_size.py"

DPATH_SCRIPTS=`dirname $0`
FPATH_DISPATCH_SCRIPT="${DPATH_SCRIPTS}/${FNAME_DISPATH_SCRIPT}"
FPATH_CCA_SCRIPT="${DPATH_SCRIPTS}/${FNAME_CCA_SCRIPT}"

if [ -z $FPATH_DISPATCH_SCRIPT ]
then
    echo "Script not found: ${FPATH_DISPATCH_SCRIPT}"
    exit 1
fi

if [ $I_BOOTSTRAP_REPETITION_MAX -gt $N_BOOTSTRAP_REPETITIONS ]
then
    echo "Invalid I_BOOTSTRAP_REPETITION_MAX: $I_BOOTSTRAP_REPETITION_MAX (cannot be greater than ${N_BOOTSTRAP_REPETITIONS})"
    exit 2
fi

if [ $I_SAMPLE_SIZE_MAX -gt $N_SAMPLE_SIZES ]
then
    echo "Invalid I_BOOTSTRAP_REPETITION_MAX: $I_BOOTSTRAP_REPETITION_MAX (cannot be greater than ${N_BOOTSTRAP_REPETITIONS})"
    exit 2
fi

for (( I_SAMPLE_SIZE=${I_SAMPLE_SIZE_MIN}; I_SAMPLE_SIZE <= ${I_SAMPLE_SIZE_MAX}; I_SAMPLE_SIZE += 1 ))
do
    for (( I_BOOTSTRAP_REPETITION=${I_BOOTSTRAP_REPETITION_MIN}; I_BOOTSTRAP_REPETITION <= ${I_BOOTSTRAP_REPETITION_MAX}; I_BOOTSTRAP_REPETITION += 1 ))
    do
        if [ $I_SAMPLE_SIZE -le 20 ]
        then
            DISPATCH_MEMORY="20G"
            DISPATCH_TIME="0:30:00"
        else
            DISPATCH_MEMORY="40G"
            DISPATCH_TIME="0:45:00"
        fi

        SUBDIRS_LOG="PCs_${N_PCS// /_}/i_sample_size_${I_SAMPLE_SIZE}"
        
        COMMAND="${FPATH_DISPATCH_SCRIPT} ${FPATH_CCA_SCRIPT} -m ${DISPATCH_MEMORY} -t ${DISPATCH_TIME} -d ${SUBDIRS_LOG} ${N_SAMPLE_SIZES} ${N_BOOTSTRAP_REPETITIONS} ${I_SAMPLE_SIZE} ${I_BOOTSTRAP_REPETITION} ${N_PCS}"
        eval ${COMMAND}
    done
done
